service-add:
    path:     /add
    defaults: { _controller: ApiBundle:Service:addServices }
    methods: [POST]

service-get-all:
    path:     /get-all
    defaults: { _controller: ApiBundle:Service:getAllServices }
    methods: [Get]

service-edit:
    path:     /edit
    defaults: { _controller: ApiBundle:Service:editService }
    methods: [PUT]

service-delete:
    path:     /{serviceId}
    defaults: { _controller: ApiBundle:Service:deleteService }
    methods: [DELETE]

service-change-position:
    path:     /change-position
    defaults: { _controller: ApiBundle:Service:changeServicePosition }
    methods: [POST]