register:
    path:     /register
    defaults: { _controller: ApiBundle:Authentication:signUp }
    methods: [POST]

email-verification:
    path:     /email-verification
    defaults: { _controller: ApiBundle:Authentication:sendVerificationMail }
    methods: [POST]

current-user:
    path:     /current-user
    defaults: { _controller: ApiBundle:Authentication:getCurrentUser }
    methods: [POST]

email-check:
    path:     /email-check/{codeGen}
    defaults: { _controller: ApiBundle:Authentication:enableAccount }
    methods: [GET]

password-recovery:
    path:     /password-recovery/{codeGen}/{lang}
    defaults: { _controller: ApiBundle:Authentication:resetPasswordRender }
    methods: [GET]

password-forgot:
    path:     /password-forgot
    defaults: { _controller: ApiBundle:Authentication:sendPasswordForgotMail }
    methods: [POST]

reset-password:
    path:     /reset-password
    defaults: { _controller: ApiBundle:Authentication:resetPassword }
    methods: [POST]

get-file:
    path:     /media/file/{fileType}/{fileName}
    defaults: { _controller: ApiBundle:Authentication:getFile }
    methods: [GET]

add-profile-photo:
    path:     /add-profile-photo
    defaults: { _controller: ApiBundle:Authentication:addPhoto }
    methods: [POST]

refresh-link:
    path:     /refresh-link/{refreshToken}/{lang}
    defaults: { _controller: ApiBundle:Authentication:refreshAccountLink }
    methods: [GET]

return-link:
    path:     /return-link/{returnToken}/{lang}
    defaults: { _controller: ApiBundle:Authentication:returnAccountLink }
    methods: [GET]

payout-paid-webhook:
    path:     /payout/{zZeendId}
    defaults: { _controller: ApiBundle:Authentication:payout }
    methods: [GET]
