post-add:
    path:     /add
    defaults: { _controller: ApiBundle:Post:newPost }
    methods: [POST]

post-get-all:
    path:     /get-all
    defaults: { _controller: ApiBundle:Post:getAllPost }
    methods: [POST]

post-current-user-get-all:
    path:     /user/get-all
    defaults: { _controller: ApiBundle:Post:getCurrentUserAllPosts }
    methods: [POST]


post-get:
    path:     /get/{postId}
    defaults: { _controller: ApiBundle:Post:getPost }
    methods: [GET]