send:
    path:     /send
    defaults: { _controller: ApiBundle:Chat:sendChat }
    methods: [POST]

z-get:
    path:     /z-get
    defaults: { _controller: ApiBundle:Chat:getChat }
    methods: [POST]

contact:
    path:     /contact
    defaults: { _controller: ApiBundle:Chat:getChatContact }
    methods: [POST]