imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ApiBundle/Resources/config/services.yml" }
    - { resource: "@WebBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@LiveBundle/Resources/config/services.yml" }


# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    site_name: "Nom de l'application" #TODO Change
    site_url: "http://192.168.2.208/zZeend/Back-End/web/app_dev.php" #TODO Change
    baseUrl: "http://192.168.2.208/zZeend/Back-End/web/app_dev.php/api"


    api_keys:
        app-source-key: 'rLxO#JGPCvY1*oH&F9D1qSiOdG50MvO&X7O*Va&vmQqhVeNVMfaeD0OxWObUemDw2GwQn@FfY*CsF3rKTf39zT7SmH9uoQp00@e'
        vonage-api-key: '47346321'
        vonage-secret-key: 'd89f84512185dfb315acc6e0ec4a7636d0074ab4'
        live-api-key: 'e875aa64-05d3-48ba-b8e0-4bfd00e28281'
        stripe-secret-key: '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'

    upload_dir: '../web/assets/uploads'

    app_mail: 'no-reply@zzeend.com'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    property_info:
        enabled: true
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        #name: PHPSESSID
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: ~
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 0
        name: SFSESSID
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

    templating:
        engines: ['twig']

    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        application_name: '%site_name%'
        site_url: '%site_url%'
    date:
        format: d.m.Y, H:i:s
        interval_format: '%%d jours'
        timezone: America/Toronto


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: utf8mb4
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: false  #'%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    disable_delivery: false
    #    delivery_address: ['adjchel@gmail.com'] //to a specifics user, never in production !!!!!!
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    port: '%mailer_port%'
    encryption: '%mailer_encryption%'
    auth_mode: login
    local_domain: zzeend.com
#    spool: { type: memory }
#    stream_options:
#        ssl:
#            allow_self_signed: true
#            verify_peer: false
#            verify_peer_name: false

sensio_framework_extra:
    router:
        annotations: false
    psr_message:
        enabled: false

nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Source-Key', 'Live-Api-Key']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': ~

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation //todo n"a pas ete fait
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification //todo n"a pas ete fait
    pass_phrase:      '%jwt_secret_phrase%' # required for token creation, usage of an environment variable is recommended //todo ne fonctionnera pas
    token_ttl:         7889400


#    Push notification types
#    1: new zZeend
#    2: request send
#    3: request accepted
#    4: request accepted
#    5: zZeend payment
#    6: zZeend finalized
#    7: canceled zZeend
#    8: edit zZeend
#    9: chat received
#    10: shared content in chat received
#    11: rate publish
#    13: video calling
#    14: video call received
#    15: video call rejected
#    16: video call back notification message (Michel said he will call you back)
#    17: video session end
#    18: zZeend payout



## for profile ---- : VPA4iST9YEAk0CiawXEKbcArkfDSBKg5Re9gfywvmK
## for post ------- : fBfqcChzEM9ai3hQvX0GC80KibabT1uU6LXtSYqpn1

