api_login_check:
    path: /api/auth/login_check

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix: /api

mailer:
    resource: "@WebBundle/Resources/config/routing.yml"
    prefix:   /web

