zzeend:
    resource: "@ZzeendBundle/Resources/config/routing.yml"
    prefix:   /

api_login_check:
    path: /api/login_check

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix: /api

mailer:
    resource: "@WebBundle/Resources/config/routing.yml"
    prefix:   /web

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

