security:
    always_authenticate_before_granting: true

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SEEKER: ROLE_USER
        ROLE_OWNER:  ROLE_USER
        ROLE_ADMIN:  [ROLE_SEEKER, ROLE_OWNER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api_register:
            pattern: ^/api/register
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern: ^/
            remember_me:
                secret:   "%secret%"
                path:     /
                always_remember_me: true
                lifetime: 1209600 # 1 week in seconds
            anonymous: true
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                #login_path: login
                check_path: fos_user_security_check
                default_target_path: crm_dashboard
            logout:
                path: fos_user_security_logout
                #target: login

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
