security:
    always_authenticate_before_granting: true

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SEEKER: ROLE_USER
        ROLE_OWNER:  ROLE_USER
        ROLE_ADMIN:  [ROLE_USER, ROLE_SEEKER, ROLE_OWNER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/auth/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/auth/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api_register:
            pattern: ^/api/auth/register
            anonymous: true

        email_verification:
            pattern: ^/api/auth/email-verification
            anonymous: true

        email_check:
            pattern: ^/api/auth/email-check
            anonymous: true

        password-forgot:
            pattern: ^/api/auth/password-forgot
            anonymous: true

        password-recovery:
            pattern: ^/api/auth/password-recovery
            anonymous: true

        reset-password:
            pattern: ^/api/auth/reset-password
            anonymous: true

        media-file:
            pattern: ^/api/auth/media/file
            anonymous: true

        add-profile-photo:
            pattern: ^/api/auth/add-profile-photo
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern: ^/
            remember_me:
                secret:   "%secret%"
                path:     /
                always_remember_me: true
                lifetime: 1209600 # 1 week in seconds
            anonymous: true
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                #login_path: login
                check_path: fos_user_security_check
                default_target_path: crm_dashboard
            logout:
                path: fos_user_security_logout
                #target: login

    access_control:
        - { path: ^/api/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/email-verification, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/email-check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/password-recovery, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/password-forgot, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/media/file, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/add-profile-photo, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
