# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
#parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    localizeddate:
        class: 'Twig_Extensions_Extension_Intl'
        tags:
            - { name: twig.extension }

    ionic_kernel_respose_listener:
        class: ApiBundle\EventListener\KernelResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, methode: onKernelResponse, priority: -1025 }
        arguments: [ "@doctrine.orm.entity_manager", "@security.token_storage" ]

    ionic_kernel_request_listener:
        class: ApiBundle\EventListener\KernelRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, methode: onKernelRequest, priority: -1025 }
        arguments: [ "%api_keys%"]