send_:
    path:     /send-req
    defaults: { _controller: ApiBundle:Request:sendRequest }
    methods: [POST]

apply-state:
    path:     /apply-state
    defaults: { _controller: ApiBundle:Request:applyRequestState }
    methods: [POST]

\all:
    path:     /all
    defaults: { _controller: ApiBundle:Request:getAllRequests }
    methods: [POST]


