Authentication:
    resource: "@ApiBundle/Resources/config/Authentication/routingAuthentication.yml"
    prefix:   /auth

service:
    resource: "@ApiBundle/Resources/config/Service/routingService.yml"
    prefix:   /services

request:
    resource: "@ApiBundle/Resources/config/Request/routingRequest.yml"
    prefix:   /request

search:
    resource: "@ApiBundle/Resources/config/Search/routingSearch.yml"
    prefix:   /search

profile:
    resource: "@ApiBundle/Resources/config/Profile/routingProfile.yml"
    prefix:   /profile

contact:
    resource: "@ApiBundle/Resources/config/Contact/routingContact.yml"
    prefix:   /contact

chat:
    resource: "@ApiBundle/Resources/config/Chat/routingChat.yml"
    prefix:   /chat

zzeend:
    resource: "@ApiBundle/Resources/config/Zzeend/routingZzeend.yml"
    prefix:   /zzeend

notification:
    resource: "@ApiBundle/Resources/config/Notification/routingNotification.yml"
    prefix:   /notification

payment_method:
    resource: "@ApiBundle/Resources/config/PaymentMethod/routingPaymentMethod.yml"
    prefix:   /payment-method

rate:
    resource: "@ApiBundle/Resources/config/Rate/routingRate.yml"
    prefix:   /rate

event:
    resource: "@ApiBundle/Resources/config/Event/routingEvent.yml"
    prefix:   /event

post:
    resource: "@ApiBundle/Resources/config/Post/routingPost.yml"
    prefix:   /post

like:
    resource: "@ApiBundle/Resources/config/Like/routingLike.yml"
    prefix:   /like

view:
    resource: "@ApiBundle/Resources/config/View/routingView.yml"
    prefix:   /view

plan:
    resource: "@ApiBundle/Resources/config/Plan/routingPlan.yml"
    prefix:   /plan

share:
    resource: "@ApiBundle/Resources/config/Share/routingShare.yml"
    prefix:   /share

menu-statistics:
    resource: "@ApiBundle/Resources/config/Statistics/routingStatistics.yml"
    prefix:   /statistics

tags:
    resource: "@ApiBundle/Resources/config/Tags/routingTags.yml"
    prefix:   /tags

indexing:
    resource: "@ApiBundle/Resources/config/Indexing/routingIndexing.yml"
    prefix:   /indexing

story:
    resource: "@ApiBundle/Resources/config/Story/routingStory.yml"
    prefix:   /story

push-notification:
    resource: "@ApiBundle/Resources/config/PushNotification/routingPushNotification.yml"
    prefix:   /push-notification

media:
    resource: "@ApiBundle/Resources/config/Media/routingMedia.yml"
    prefix:   /media