register:
    path:     /register
    defaults: { _controller: ApiBundle:Default:signUp }
    methods: [POST]

service_search:
    path:     /service_search
    defaults: { _controller: ApiBundle:Default:signUp }
    methods: [POST]
