Authentication:
    resource: "@ApiBundle/Resources/config/Authentication/routingAuthentication.yml"
    prefix:   /auth

service:
    resource: "@ApiBundle/Resources/config/Service/routingService.yml"
    prefix:   /services

request:
    resource: "@ApiBundle/Resources/config/Request/routingRequest.yml"
    prefix:   /request

search:
    resource: "@ApiBundle/Resources/config/Search/routingSearch.yml"
    prefix:   /search

profile:
    resource: "@ApiBundle/Resources/config/Profile/routingProfile.yml"
    prefix:   /profile

contact:
    resource: "@ApiBundle/Resources/config/Contact/routingContact.yml"
    prefix:   /contact

chat:
    resource: "@ApiBundle/Resources/config/Chat/routingChat.yml"
    prefix:   /chat