register:
    path:     /register
    defaults: { _controller: ApiBundle:Api:signUp }
    methods: [POST]

email-verification:
    path:     /email-verification
    defaults: { _controller: ApiBundle:Api:sendVerificationMail }
    methods: [POST]

current-user:
    path:     /current-user
    defaults: { _controller: ApiBundle:Api:getCurrentUser }
    methods: [POST]

email-check:
    path:     /email-check/{codeGen}
    defaults: { _controller: ApiBundle:Api:enableAccount }
    methods: [GET]

password-recovery:
    path:     /password-recovery/{codeGen}
    defaults: { _controller: ApiBundle:Api:resetPasswordRender }
    methods: [GET]

password-forgot:
    path:     /password-forgot
    defaults: { _controller: ApiBundle:Api:sendPasswordForgotMail }
    methods: [POST]

reset-password:
    path:     /reset-password
    defaults: { _controller: ApiBundle:Api:resetPassword }
    methods: [POST]

service-search:
    path:     /service-search
    defaults: { _controller: ApiBundle:Api:serviceSearch }
    methods: [POST]

user-profile:
    path:     /user-profile
    defaults: { _controller: ApiBundle:Api:userProfile }
    methods: [POST]

add-user-services:
    path:     /add-user-services
    defaults: { _controller: ApiBundle:Api:addUserServices }
    methods: [POST]

send-request:
    path:     /send-request
    defaults: { _controller: ApiBundle:Api:sendRequest }
    methods: [POST]

request-state:
    path:     /request-state
    defaults: { _controller: ApiBundle:Api:changeRequestState }
    methods: [POST]


