services:
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    ionicapi.jsonManager:
      class: ApiBundle\Manager\JsonManager
      arguments: [ 11 ]

    ionicapi.notificationManager:
      class: ApiBundle\Manager\NotificationManager
      arguments: [ "@doctrine.orm.entity_manager" ]

    ionicapi.tokenGeneratorManager:
      class: ApiBundle\Manager\TokenGeneratorManager

    ionicapi.fileUploaderManager:
      class: ApiBundle\Manager\FileUploaderManager

    ionicapi.push.notification.manager:
      class: ApiBundle\Manager\PushNotificationManager

    ionicapi.emailManager:
      class: ApiBundle\Manager\EmailManager
      arguments:
        [ '@service_container' ]