services:
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    ionicapi.jsonManager:
      class: ApiBundle\Manager\JsonManager
      arguments: [ 11 ]

    ionicapi.notificationManager:
      class: ApiBundle\Manager\NotificationManager
      arguments: [ "@doctrine.orm.entity_manager" ]

    ionicapi.tokenGenerator:
      class: ApiBundle\Manager\TokenGenerator
      arguments: [ 11 ]

    ionicapi.fileUploader:
      class: ApiBundle\Manager\FileUploader
      arguments: [ 11 ]
