<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * VersionControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionControlRepository extends \Doctrine\ORM\EntityRepository
{
    public function GetQueryBuilder()
    {
        return $queryBuilder = $this->createQueryBuilder('v');
    }

}
