add-tags:
    path:     /add
    defaults: { _controller: ApiBundle:Tags:addTags }
    methods: [POST]

get-all:
    path:     /
    defaults: { _controller: ApiBundle:Tags:getAllTags }
    methods: [GET]

edit-tag:
    path:     /edit
    defaults: { _controller: ApiBundle:Tags:editTag }
    methods: [PUT]

delete-tag:
    path:     /{tagId}
    defaults: { _controller: ApiBundle:Tags:deleteTag }
    methods: [Delete]

change-position-tag:
    path:     /change-position
    defaults: { _controller: ApiBundle:Tags:changePosition }
    methods: [Post]

