plan-get-all:
    path:     /all
    defaults: { _controller: ApiBundle:Plan:getPlans }
    methods: [GET]

plan-get-subscription:
    path:     /subscription
    defaults: { _controller: ApiBundle:Plan:getUserSubscription }
    methods: [GET]

plan-get-subscribe:
    path:     /subscribe
    defaults: { _controller: ApiBundle:Plan:planSubscribe }
    methods: [POST]

plan-get-update:
    path:     /update
    defaults: { _controller: ApiBundle:Plan:updatePlanSubscription }
    methods: [PUT]

get-payment:
    path:     /payment
    defaults: { _controller: ApiBundle:Plan:planSubscriptionPayment }
    methods: [POST]

plan-taxes:
    path:     /taxes
    defaults: { _controller: ApiBundle:Plan:makeTaxes }
    methods: [POST]
