pmth-add:
    path:     /add
    defaults: { _controller: ApiBundle:PaymentMethod:addPaymentMethod }
    methods: [POST]

pmth-update:
    path:     /update
    defaults: { _controller: ApiBundle:PaymentMethod:updatePaymentMethod }
    methods: [POST]

pmth-delete:
    path:     /delete
    defaults: { _controller: ApiBundle:PaymentMethod:deletePaymentMethod }
    methods: [POST]

pmth-get-all:
    path:     /get-all
    defaults: { _controller: ApiBundle:PaymentMethod:getAllPaymentMethods }
    methods: [POST]

pmth-state:
    path:     /apply-state
    defaults: { _controller: ApiBundle:PaymentMethod:applyState }
    methods: [POST]