add:
    path:     /add
    defaults: { _controller: ApiBundle:PaymentMethod:addPaymentMethod }
    methods: [POST]

update:
    path:     /update
    defaults: { _controller: ApiBundle:PaymentMethod:updatePaymentMethod }
    methods: [POST]

delete:
    path:     /delete
    defaults: { _controller: ApiBundle:PaymentMethod:deletePaymentMethod }
    methods: [POST]

mth-get-all:
    path:     /get-all
    defaults: { _controller: ApiBundle:PaymentMethod:getAllPaymentMethods }
    methods: [POST]

mth-state:
    path:     /apply-state
    defaults: { _controller: ApiBundle:PaymentMethod:applyState }
    methods: [POST]