pmth-add:
    path:     /add
    defaults: { _controller: ApiBundle:PaymentMethod:addPaymentMethod }
    methods: [POST]

pmth-update:
    path:     /update
    defaults: { _controller: ApiBundle:PaymentMethod:updatePaymentMethod }
    methods: [POST]

pmth-delete:
    path:     /delete
    defaults: { _controller: ApiBundle:PaymentMethod:deletePaymentMethod }
    methods: [POST]

pmth-get-all:
    path:     /get-all
    defaults: { _controller: ApiBundle:PaymentMethod:getAllPaymentMethods }
    methods: [POST]

apply-state:
    path:     /apply-state
    defaults: { _controller: ApiBundle:PaymentMethod:applyState }
    methods: [POST]

create-stripe-connected-account:
    path:     /create-stripe-connected-account
    defaults: { _controller: ApiBundle:PaymentMethod:createStripeUserConnectedAccount }
    methods: [POST]

get_user-stripe-connected-account:
    path:     /get-stripe-connected-account
    defaults: { _controller: ApiBundle:PaymentMethod:getUserStripeConnectedAccount }
    methods: [POST]

create_user-stripe-account-like:
    path:     /create-stripe-account-link
    defaults: { _controller: ApiBundle:PaymentMethod:createAccountLink }
    methods: [POST]