profile:
    path:     /get
    defaults: { _controller: ApiBundle:Profile:getProfile }
    methods: [POST]

get-user:
    path:     /get-user
    defaults: { _controller: ApiBundle:Profile:getCurrentUser }
    methods: [POST]

update-profile:
    path:     /update
    defaults: { _controller: ApiBundle:Profile:updateCurrentUser }
    methods: [PUT]

visibility:
    path:     /visibility
    defaults: { _controller: ApiBundle:Profile:visibility }
    methods: [PUT]

add-social-netoword:
    path:     /social-network/add
    defaults: { _controller: ApiBundle:Profile:addSocialNetwork }
    methods: [POST]

get-all-social-netoword:
    path:     /social-network/get-all
    defaults: { _controller: ApiBundle:Profile:getAllSocialNetwork }
    methods: [POST]

upgrade-ccount:
    path:     /upgrade-account
    defaults: { _controller: ApiBundle:Profile:upgradeAccount }
    methods: [POST]


#view-get-all:
#    path:     /get-all
#    defaults: { _controller: ApiBundle:Post:getAllPost }
#    methods: [GET]

