profile:
    path:     /get
    defaults: { _controller: ApiBundle:Profile:getProfile }
    methods: [POST]

get-user:
    path:     /get-user
    defaults: { _controller: ApiBundle:Profile:getCurrentUser }
    methods: [POST]

update-profile:
    path:     /update
    defaults: { _controller: ApiBundle:Profile:updateCurrentUser }
    methods: [PUT]

visibility:
    path:     /visibility
    defaults: { _controller: ApiBundle:Profile:visibility }
    methods: [PUT]

add-social-netoword:
    path:     /social-netowk/add
    defaults: { _controller: ApiBundle:Profile:addSocialNetwork }
    methods: [POST]

update-social-netoword:
    path:     /social-netowk/update
    defaults: { _controller: ApiBundle:Profile:updateSocialNetwork }
    methods: [PUT]

delete-social-netoword:
    path:     /social-netowk/delete
    defaults: { _controller: ApiBundle:Profile:deleteSocialNetwork }
    methods: [DELETE]
